
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- require "user.cmp"
-- require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.harpoon"
require "user.nvim-tree"
require "user.nvim-ufo"
require "user.cbox"
require "user.indent-guides"
require "user.mini-align"
